[tool.poetry]
name = "orchestrator"
version = "0.1.0"
description = ""
authors = ["zhutoutoutousan <mxyuiiu64545@126.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
llama-index = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
